default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :test do
    scan(
      project: "AsiaShop.xcodeproj",
      scheme: "AsiaShop",
      devices: ["iPhone 17 Pro"]
    )
  end

  desc "Build app for distribution"
  lane :build do
    gym(
      project: "AsiaShop.xcodeproj",
      scheme: "AsiaShop"
    )
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "J62PGDU769",
      issuer_id: "1a445c90-98e9-4289-b408-e2430ecb0569",
      key_filepath: "fastlane/AuthKey_J62PGDU769.p8"
    )

    scan(
      project: "AsiaShop.xcodeproj",
      scheme: "AsiaShop",
      devices: ["iPhone 17 Pro"]
    )

    gym(
      project: "AsiaShop.xcodeproj",
      scheme: "AsiaShop",
      export_method: "app-store",
      export_team_id: "5YQ567888B",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          "Roman.AsiaShop" => "AsiaShop Distribution"
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      changelog: "New build from fastlane"
    )
  end
end